"""update schema with spanish enums and models

Revision ID: 92c3fa671428
Revises: 
Create Date: 2026-04-05 09:43:26.113806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c3fa671428'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.UUID(), nullable=False),
    sa.Column('tipo_actor', sa.Enum('CLIENTE', 'TALLER', 'ADMINISTRADOR', 'SISTEMA', name='tipo_actor'), nullable=False),
    sa.Column('id_actor', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('entidad_afectada', sa.String(length=100), nullable=False),
    sa.Column('id_entidad_afectada', sa.UUID(), nullable=True),
    sa.Column('resultado', sa.Enum('EXITO', 'ERROR', 'ADVERTENCIA', name='resultado_auditoria'), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('ip_origen', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('fecha_evento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_table('especialidad',
    sa.Column('id_especialidad', sa.UUID(), nullable=False),
    sa.Column('nombre_especialidad', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estado_especialidad'), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidad'),
    sa.UniqueConstraint('nombre_especialidad')
    )
    op.create_table('servicio',
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('nombre_servicio', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'INACTIVO', name='service_status'), nullable=False),
    sa.PrimaryKeyConstraint('id_servicio'),
    sa.UniqueConstraint('nombre_servicio')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('CLIENTE', 'TALLER', 'ADMINISTRADOR', name='rol_usuario'), nullable=False),
    sa.Column('es_activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token', sa.String(length=500), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_table('cliente',
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('ci', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('foto_perfil_url', sa.String(length=1000), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('id_usuario')
    )
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.UUID(), nullable=False),
    sa.Column('tipo_usuario_destino', sa.String(length=50), nullable=False),
    sa.Column('id_usuario_destino', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo_notificacion', sa.Enum('PUSH', 'INTERNA', 'EMAIL', name='notification_type'), nullable=False),
    sa.Column('categoria_evento', sa.Enum('SOLICITUD', 'POSTULACION', 'ASIGNACION', 'ESTADO', 'SISTEMA', name='notification_category'), nullable=False),
    sa.Column('referencia_entidad', sa.String(length=100), nullable=True),
    sa.Column('referencia_id', sa.UUID(), nullable=True),
    sa.Column('estado_lectura', sa.Enum('LEIDA', 'NO_LEIDA', name='notification_read_status'), nullable=False),
    sa.Column('estado_envio', sa.Enum('ENVIADA', 'FALLIDA', 'PENDIENTE', name='notification_send_status'), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_table('taller',
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.Column('nombre_taller', sa.String(length=255), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('estado_aprobacion', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estado_aprobacion_taller'), nullable=False),
    sa.Column('estado_operativo', sa.Enum('DISPONIBLE', 'NO_DISPONIBLE', 'SUSPENDIDO', name='estado_operativo_taller'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_taller'),
    sa.UniqueConstraint('id_usuario'),
    sa.UniqueConstraint('nit')
    )
    op.create_table('estadistica_resumen',
    sa.Column('id_estadistica', sa.UUID(), nullable=False),
    sa.Column('tipo_estadistica', sa.Enum('TALLER', 'GENERAL', name='tipo_estadistica'), nullable=False),
    sa.Column('periodo', sa.Enum('DIA', 'SEMANA', 'MES', name='estadistica_periodo'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=True),
    sa.Column('metrica', sa.String(length=255), nullable=False),
    sa.Column('valor_numerico', sa.Integer(), nullable=True),
    sa.Column('valor_texto', sa.String(length=1000), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_estadistica')
    )
    op.create_table('taller_especialidad',
    sa.Column('id_taller_especialidad', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_especialidad', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estado_taller_especialidad'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id_especialidad'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_taller_especialidad'),
    sa.UniqueConstraint('id_taller', 'id_especialidad', name='uq_taller_especialidad')
    )
    op.create_table('taller_servicio',
    sa.Column('id_taller_servicio', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_servicio', sa.UUID(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_taller_servicio'),
    sa.UniqueConstraint('id_taller', 'id_servicio', name='uq_taller_servicio')
    )
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo_combustible', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('estado_registro', sa.Enum('ACTIVO', 'INACTIVO', name='vehicle_registration_status'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_vehiculo')
    )
    op.create_index(op.f('ix_vehiculo_placa'), 'vehiculo', ['placa'], unique=True)
    op.create_table('solicitud_emergencia',
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('id_cliente', sa.UUID(), nullable=False),
    sa.Column('id_vehiculo', sa.UUID(), nullable=True),
    sa.Column('codigo_solicitud', sa.String(length=50), nullable=False),
    sa.Column('descripcion_texto', sa.Text(), nullable=True),
    sa.Column('descripcion_audio_url', sa.String(length=1000), nullable=True),
    sa.Column('transcripcion_audio', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('direccion_referencial', sa.String(length=500), nullable=True),
    sa.Column('estado_actual', sa.Enum('REGISTRADA', 'EN_BUSQUEDA', 'EN_ESPERA_RESPUESTAS', 'TALLER_SELECCIONADO', 'EN_CAMINO', 'EN_PROCESO', 'ATENDIDA', 'CANCELADA', name='estado_solicitud'), nullable=False),
    sa.Column('nivel_urgencia', sa.Enum('BAJO', 'MEDIO', 'ALTO', 'CRITICO', name='nivel_urgencia'), nullable=False),
    sa.Column('categoria_incidente', sa.String(length=255), nullable=True),
    sa.Column('radio_busqueda_km', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id_vehiculo'], ),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_index(op.f('ix_solicitud_emergencia_codigo_solicitud'), 'solicitud_emergencia', ['codigo_solicitud'], unique=True)
    op.create_table('clasificacion_incidente',
    sa.Column('id_clasificacion', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('categoria_predicha', sa.String(length=255), nullable=False),
    sa.Column('subcategoria_predicha', sa.String(length=255), nullable=True),
    sa.Column('id_especialidad_requerida', sa.UUID(), nullable=True),
    sa.Column('id_servicio_sugerido', sa.UUID(), nullable=True),
    sa.Column('nivel_urgencia_predicho', sa.String(length=50), nullable=True),
    sa.Column('confianza_modelo', sa.Float(), nullable=True),
    sa.Column('modelo_utilizado', sa.String(length=255), nullable=True),
    sa.Column('fuente_entrada', sa.String(length=50), nullable=False),
    sa.Column('resultado_json', sa.Text(), nullable=True),
    sa.Column('fecha_procesamiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_especialidad_requerida'], ['especialidad.id_especialidad'], ),
    sa.ForeignKeyConstraint(['id_servicio_sugerido'], ['servicio.id_servicio'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_clasificacion')
    )
    op.create_table('evidencia',
    sa.Column('id_evidencia', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('tipo_evidencia', sa.Enum('IMAGEN', 'AUDIO', 'VIDEO', 'DOCUMENTO', name='evidence_type'), nullable=False),
    sa.Column('url_archivo', sa.String(length=1000), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamano_bytes', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('origen', sa.Enum('CLIENTE', 'TALLER', 'SISTEMA', name='evidence_origin'), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_evidencia')
    )
    op.create_table('historial_estado_solicitud',
    sa.Column('id_historial_estado', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', sa.Enum('REGISTRADA', 'EN_BUSQUEDA', 'EN_ESPERA_RESPUESTAS', 'TALLER_SELECCIONADO', 'EN_CAMINO', 'EN_PROCESO', 'ATENDIDA', 'CANCELADA', name='request_status'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('REGISTRADA', 'EN_BUSQUEDA', 'EN_ESPERA_RESPUESTAS', 'TALLER_SELECCIONADO', 'EN_CAMINO', 'EN_PROCESO', 'ATENDIDA', 'CANCELADA', name='request_status'), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('actualizado_por_tipo', sa.Enum('CLIENTE', 'TALLER', 'ADMINISTRADOR', 'SISTEMA', name='actor_type'), nullable=False),
    sa.Column('actualizado_por_id', sa.UUID(), nullable=True),
    sa.Column('fecha_cambio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_historial_estado')
    )
    op.create_table('postulacion_taller',
    sa.Column('id_postulacion', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('tiempo_estimado_llegada_min', sa.Integer(), nullable=True),
    sa.Column('mensaje_propuesta', sa.Text(), nullable=True),
    sa.Column('estado_postulacion', sa.Enum('POSTULADA', 'RETIRADA', 'ACEPTADA', 'RECHAZADA', 'EXPIRADA', name='estado_postulacion'), nullable=False),
    sa.Column('fecha_postulacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_postulacion')
    )
    op.create_table('asignacion_atencion',
    sa.Column('id_asignacion', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('id_taller', sa.UUID(), nullable=False),
    sa.Column('id_postulacion', sa.UUID(), nullable=False),
    sa.Column('estado_asignacion', sa.Enum('ACTIVA', 'CANCELADA', 'FINALIZADA', name='estado_asignacion'), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_inicio_atencion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_fin_atencion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cancelacion', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_postulacion'], ['postulacion_taller.id_postulacion'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id_taller'], ),
    sa.PrimaryKeyConstraint('id_asignacion')
    )
    op.create_table('resultado_servicio',
    sa.Column('id_resultado_servicio', sa.UUID(), nullable=False),
    sa.Column('id_asignacion', sa.UUID(), nullable=False),
    sa.Column('id_solicitud', sa.UUID(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('solucion_aplicada', sa.Text(), nullable=True),
    sa.Column('estado_resultado', sa.Enum('RESUELTO', 'PARCIAL', 'PENDIENTE', name='estado_resultado'), nullable=False),
    sa.Column('requiere_seguimiento', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignacion_atencion.id_asignacion'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitud_emergencia.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_resultado_servicio')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_servicio')
    op.drop_table('asignacion_atencion')
    op.drop_table('postulacion_taller')
    op.drop_table('historial_estado_solicitud')
    op.drop_table('evidencia')
    op.drop_table('clasificacion_incidente')
    op.drop_index(op.f('ix_solicitud_emergencia_codigo_solicitud'), table_name='solicitud_emergencia')
    op.drop_table('solicitud_emergencia')
    op.drop_index(op.f('ix_vehiculo_placa'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_table('taller_servicio')
    op.drop_table('taller_especialidad')
    op.drop_table('estadistica_resumen')
    op.drop_table('taller')
    op.drop_table('notificacion')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('servicio')
    op.drop_table('especialidad')
    op.drop_table('bitacora')
    # ### end Alembic commands ###
